### PR TITLE
v2 added ability to setting up headers

### PR DESCRIPTION
**Pull request by azyoskol**
Just added missed methods for options

### CODE REVIEW

**Review by flc1125 — CHANGES_REQUESTED** [review]
Please adjust to pass the detection of golangci.

**Comment by azyoskol** [comment]
Done. 
Sorry, I forgot run gofmt before create PR. 
In my nvim config, I disabled option for format document.

**Review by flc1125 — APPROVED** [review]
LGTM

**Comment by flc1125** [comment]
Thanks

**Pull request merged**
